### ISSUE TITLE
Option to keep "disallowed" atRules

### ISSUE THREAD

**Issue by larvanitis** [mistakster/postcss-unwrap-at-media#3]
Would you please consider an additional option to keep any non-unwrapped media?
Something like `removeDisallowed: false` which could be `true` by default so that it doesn't break existing code.

I can see 3 use cases:
1. Unwrap everything - the default
2. Unwrap some, while leaving the rest untouched - this is what this request is about
3. Unwrap some, while removing the rest

---

Extra...

The API would be more straightforward this way (breaking change - maybe at some later major revision).

```typescript
type FilterFn = (AtRule) => boolean;

type Options = {
  filter?: string | FilterFn | Array<string | FilterFn>, // default : () => true
  removeOther?: boolean // default: false
}
```

**Comment by mistakster** [comment]
Hi! I made the plugin to do the one simple thing—get rid of media queries from the file. In real life, I found that some of them should be removed to get the correct CSS file for the desktop.

Sorry, I don't see any points do implement your request. I don't understand what kind of task you are going to solve with this. From my perspective, it's better to make your own plugin. Feel free to copy my code and build your logic on top of it.

Cheers!
